version: "3"
services:
  sipaias_web:
    container_name: sipaias_web
    image: ghcr.io/andreaszico/sipaias-fun:latest
    networks:
      - app-network
  webserver:
    container_name: webserver
    image: ghcr.io/andreaszico/nginx-sipaias:latest
    ports:
      - 80:80
    depends_on:
      - sipaias_web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
